using System;
using System.Text.RegularExpressions;

namespace UI_Demo;

/*
/// <remarks>
/// Pattern:<br/>
/// <code>(?&lt;=^[^"]*(?:"[^"]*"[^"]*)*) (?=(?:[^"]*"[^"]*")*[^"]*$)</code><br/>
/// Explanation:<br/>
/// <code>
/// ○ Zero-width positive lookbehind.<br/>
///     ○ Loop greedily any number of times right-to-left.<br/>
///         ○ Match a character other than '"' greedily any number of times right-to-left.<br/>
///         ○ Match '"' right-to-left.<br/>
///         ○ Match a character other than '"' greedily any number of times right-to-left.<br/>
///         ○ Match '"' right-to-left.<br/>
///     ○ Match a character other than '"' greedily any number of times right-to-left.<br/>
///     ○ Match if at the beginning of the string.<br/>
/// ○ Match ' '.<br/>
/// ○ Zero-width positive lookahead.<br/>
///     ○ Loop greedily any number of times.<br/>
///         ○ Match a character other than '"' atomically any number of times.<br/>
///         ○ Match '"'.<br/>
///         ○ Match a character other than '"' atomically any number of times.<br/>
///         ○ Match '"'.<br/>
///     ○ Match a character other than '"' greedily any number of times.<br/>
///     ○ Match if at the end of the string or if before an ending newline.<br/>
/// </code>
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "8.0.12.6609")]
public static partial global::System.Text.RegularExpressions.Regex SpaceSplit() => global::System.Text.RegularExpressions.Generated.SpaceSplit_1.Instance;
*/

/// <summary>
/// These cause compile-time errors until they're auto-generated by the IDE.
/// </summary>
public static partial class RegexHelpers
{
    [GeneratedRegex("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[\\-`\\]~\\[!@#$%^\\&*()\\\\_+={}:;<,>.?/|'\\\"])(?=.{8,})")]
    public static partial Regex StrongPassword();


    [GeneratedRegex(@"\w:\w")]
    public static partial Regex AlternateStream();


    [GeneratedRegex("(?<=^[^\"]*(?:\"[^\"]*\"[^\"]*)*) (?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)")]
    public static partial Regex SpaceSplit();

    
    [GeneratedRegex(@"^\\\\\?\\[^\\]*\\?")]
    public static partial Regex WindowsPath();


    [GeneratedRegex(@"^[A-Z]:\\\$Recycle\.Bin\\", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    public static partial Regex RecycleBinPath();


    [GeneratedRegex(@"^(?!/)(?!.*//)[^\000-\037\177 ~^:?*[]+(?!.*\.\.)(?!.*@\{)(?!.*\\)(?<!/\.)(?<!\.)(?<!/)(?<!\.lock)$")]
    public static partial Regex GitBranchName();


    [GeneratedRegex(@"\s+")]
    public static partial Regex WhitespaceAtLeastOnce();


    [GeneratedRegex(@"\s*\(\w:\)$")]
    public static partial Regex DriveLetter();
}
